# Flow colorscheme | Alacritty
# https://github.com/0xstepit/flow.nvim

# Black and white
[colors.primary]
background = '#d1dbe0'
foreground = '#3d505c'

# Normal colors
[colors.normal]
black = '#f2f2f2'
red = '#c98288'
green = '#88c982'
yellow = '#c9c982'
blue = '#82acc9'
magenta = '#a682c9'
cyan = '#82c9b8'
white = '#0d0d0d'

# Bright colors
[colors.bright]
black = '#f2f2f2'
red = '#c98288'
green = '#88c982'
yellow = '#c9c982'
blue = '#82acc9'
magenta = '#a682c9'
cyan = '#82c9b8'
white = '#0d0d0d'

# Search colors
[colors.search.matches]
foreground = '#ff6a00'
background = '#f2f2f2'

[colors.search.focused_match]
foreground = '#f2f2f2'
background = '#ff6a00'

# Selection colors
[colors.selection]
background = '#ff6a00'
text = '#f2f2f2'

# Cursors
# If you don't want to override original behavior, which is nice,
# remove [colors.cursor] and [colors.vi_mode_cursor].
[colors.cursor]
cursor = '#ff6a00'
text = '#f2f2f2'

[colors.vi_mode_cursor]
cursor = '#ff6a00'
text = '#f2f2f2'

[colors.footer_bar]
foreground = '#ff6a00'
background = '#f2f2f2'

# Purple color
[[colors.indexed_colors]]
index = 93
color = '#a682c9'

# Fluo Colors
[[colors.indexed_colors]]
index = 198
color = '#ff6a00'
