# Flow colorscheme | Alacritty
# https://github.com/0xstepit/flow.nvim

# Black and white
[colors.primary]
background = '#1B2228'
foreground = '#B2C1CC'

# Normal colors
[colors.normal]
black = '#0D0D0D'
red = '#F07580'
green = '#80F075'
yellow = '#F0E575'
blue = '#75BDF0'
magenta = '#A875F0'
cyan = '#75F0E6'
white = '#F2F2F2'

# Bright colors
[colors.bright]
black = '#0D0D0D'
red = '#F07580'
green = '#80F075'
yellow = '#F0E575'
blue = '#75BDF0'
magenta = '#A875F0'
cyan = '#75F0E6'
white = '#F2F2F2'

# Fluo Colors
[[colors.indexed_colors]]
index = 198
color = '#FF007C'
