# Flow colorscheme | Alacritty
# https://github.com/0xstepit/flow.nvim

# Black and white
[colors.primary]
background = '#1f282e'
foreground = '#b3c2cc'

# Normal colors
[colors.normal]
black = '#0d0d0d'
red = '#cc666e'
green = '#6fcc66'
yellow = '#cccc66'
blue = '#66a2cc'
magenta = '#9966cc'
cyan = '#66ccb3'
white = '#f2f2f2'

# Bright colors
[colors.bright]
black = '#0d0d0d'
red = '#cc666e'
green = '#6fcc66'
yellow = '#cccc66'
blue = '#66a2cc'
magenta = '#9966cc'
cyan = '#66ccb3'
white = '#f2f2f2'

# Search colors
[colors.search.matches]
foreground = '#ff6a00'
background = '#0d0d0d'

[colors.search.focused_match]
foreground = '#0d0d0d'
background = '#ff6a00'

# Selection colors
[colors.selection]
background = '#ff6a00'
text = '#0d0d0d'

# Cursors
# If you don't want to override original behavior, which is nice,
# remove [colors.cursor] and [colors.vi_mode_cursor].
[colors.cursor]
cursor = '#ff6a00'
text = '#0d0d0d'

[colors.vi_mode_cursor]
cursor = '#ff6a00'
text = '#0d0d0d'

[colors.footer_bar]
foreground = '#ff6a00'
background = '#0d0d0d'

# Purple color
[[colors.indexed_colors]]
index = 93
color = '#9966cc'

# Fluo Colors
[[colors.indexed_colors]]
index = 198
color = '#ff6a00'
