# Flow colorscheme | Alacritty
# https://github.com/0xstepit/flow.nvim

# Black and white
[colors.primary]
background = '#1b2228'
foreground = '#b3c1cc'

# Normal colors
[colors.normal]
black = '#0d0d0d'
red = '#d98c93'
green = '#93d98c'
yellow = '#d9d28c'
blue = '#8cb9d9'
magenta = '#ac8cd9'
cyan = '#8cd9d2'
white = '#f2f2f2'

# Bright colors
[colors.bright]
black = '#0d0d0d'
red = '#d98c93'
green = '#93d98c'
yellow = '#d9d28c'
blue = '#8cb9d9'
magenta = '#ac8cd9'
cyan = '#8cd9d2'
white = '#f2f2f2'

# Search colors
[colors.search.matches]
foreground = '#00e1ff'
background = '#0d0d0d'

[colors.search.focused_match]
foreground = '#0d0d0d'
background = '#00e1ff'

# Selection colors
[colors.selection]
background = '#00e1ff'
text = '#0d0d0d'

# Cursors
# If you don't want to override original behavior, which is nice,
# remove [colors.cursor] and [colors.vi_mode_cursor].
[colors.cursor]
cursor = '#00e1ff'
text = '#0d0d0d'

[colors.vi_mode_cursor]
cursor = '#00e1ff'
text = '#0d0d0d'

[colors.footer_bar]
foreground = '#00e1ff'
background = '#0d0d0d'

# Purple color
[[colors.indexed_colors]]
index = 93
color = '#ac8cd9'

# Fluo Colors
[[colors.indexed_colors]]
index = 198
color = '#00e1ff'
